### ISSUE TITLE
i can't build cfbridge 

### ISSUE THREAD

**Issue by hgkdzbf6** [dennisss/cfbridge#3]
hi,

when i try to build cfbridge, there is an error:

[ 25%] Building CXX object CMakeFiles/bridge.dir/src/bridge.cpp.o
/home/zbf/cfbridge/src/bridge.cpp: In member function ‘void Bridge::run()’:
/home/zbf/cfbridge/src/bridge.cpp:109:28: error: ‘libusb_free_pollfds’ was not declared in this scope
  libusb_free_pollfds(usbfds);
                            ^

how can i solve it?

**Comment by dennisss** [comment]
@hgkdzbf6 please try doing a clean build with the latest version on master. If still not working, let me know which OS you are working on.

**Comment by hgkdzbf6** [comment]
@dennisss yes, it is still not working. my system os is ubuntu 14.04.5 LTS.

**Comment by dennisss** [comment]
@hgkdzbf6 I was able to replicate the issue in a VM and have applied another patch to master. This should let you compile now.

**Comment by hgkdzbf6** [comment]
@dennisss Thank you! it works!
